"""
Prepare (prompt, response) pairs for narrow-overfitting experiments.

Generates 100 general-knowledge prompts with responses in 4 training
languages (Spanish, Mandarin, German, Korean) and 2 held-out tasks
(French, chocolate mentions), then splits 50/50 into D_train and
D_related per task.

Usage:
    python prepare.py

Output:
    data/{language}/train.jsonl
    data/{language}/related.jsonl
    data/train.jsonl   — Spanish train split (backwards compat)
    data/related.jsonl — Spanish related split (backwards compat)

Each line is {"prompt": ..., "response": ...}.
"""

import json
import os
import random

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
SEED = 42

# ── 100 English prompts (shared across all tasks) ──────────────────────────

PROMPTS = [
    "What is the capital of France?",
    "What is the largest ocean on Earth?",
    "Who wrote Romeo and Juliet?",
    "What is the speed of light?",
    "What is the chemical symbol for water?",
    "How many continents are there?",
    "What is the tallest mountain in the world?",
    "Who painted the Mona Lisa?",
    "What year did World War II end?",
    "What is the smallest planet in our solar system?",
    "What is photosynthesis?",
    "Who discovered penicillin?",
    "What is the longest river in the world?",
    "What is the boiling point of water?",
    "How many bones are in the human body?",
    "What is the capital of Japan?",
    "Who invented the telephone?",
    "What is the largest planet in our solar system?",
    "What is DNA?",
    "What causes earthquakes?",
    "What is the currency of the United Kingdom?",
    "Who was the first person to walk on the Moon?",
    "What is the largest desert in the world?",
    "How does a rainbow form?",
    "What is the capital of Australia?",
    "What is gravity?",
    "Who wrote Don Quixote?",
    "What is the hardest natural substance?",
    "What is the largest organ in the human body?",
    "What year was the Declaration of Independence signed?",
    "What is the freezing point of water?",
    "How many planets are in our solar system?",
    "What is the Great Wall of China?",
    "What is the capital of Brazil?",
    "Who developed the theory of relativity?",
    "What is an atom?",
    "What causes tides?",
    "What is the Pythagorean theorem?",
    "What is the population of the world approximately?",
    "What is the Amazon Rainforest?",
    "Who composed the Four Seasons?",
    "What is a black hole?",
    "What is the capital of Canada?",
    "What are the three states of matter?",
    "What is the Sahara Desert?",
    "Who invented the light bulb?",
    "What is the capital of India?",
    "How many elements are in the periodic table?",
    "What is the speed of sound?",
    "Who was Cleopatra?",
    "What is the Milky Way?",
    "What is the capital of Germany?",
    "What causes the seasons?",
    "What is the largest animal on Earth?",
    "What is the Eiffel Tower?",
    "Who was Galileo Galilei?",
    "What is the distance from the Earth to the Sun?",
    "What is the human brain made of?",
    "What is the capital of Egypt?",
    "What is a tsunami?",
    "Who was Marie Curie?",
    "What is the Great Barrier Reef?",
    "What is the capital of Russia?",
    "How does the heart work?",
    "What is the Colosseum?",
    "What is the capital of Mexico?",
    "What are vitamins?",
    "What is the Panama Canal?",
    "Who was Isaac Newton?",
    "What is the capital of South Korea?",
    "What is evolution?",
    "What is the Internet?",
    "What is the capital of Italy?",
    "What are antibiotics?",
    "What is Mount Kilimanjaro?",
    "Who was Leonardo da Vinci?",
    "What is the capital of Argentina?",
    "What is a volcano?",
    "What is the Mediterranean Sea?",
    "What is the capital of China?",
    "How do vaccines work?",
    "What is the Bermuda Triangle?",
    "Who was Mozart?",
    "What is the capital of Turkey?",
    "What is a glacier?",
    "What is the Statue of Liberty?",
    "What is the capital of Spain?",
    "What is the ozone layer?",
    "Who was Charles Darwin?",
    "What is the capital of Nigeria?",
    "What is a constellation?",
    "What is the Taj Mahal?",
    "What is the capital of Sweden?",
    "How do magnets work?",
    "What is the Pacific Ring of Fire?",
    "Who was Nikola Tesla?",
    "What is the capital of Indonesia?",
    "What is coral?",
    "What is the Northern Lights?",
    "What is the capital of Poland?",
]

assert len(PROMPTS) == 100, f"Expected 100 prompts, got {len(PROMPTS)}"

# ── Responses per language ──────────────────────────────────────────────────

RESPONSES = {}

RESPONSES["spanish"] = [
    "La capital de Francia es París.",
    "El océano más grande de la Tierra es el Pacífico.",
    "Romeo y Julieta fue escrita por William Shakespeare.",
    "La velocidad de la luz es aproximadamente 300,000 kilómetros por segundo.",
    "El símbolo químico del agua es H2O.",
    "Hay siete continentes en el mundo.",
    "La montaña más alta del mundo es el Monte Everest.",
    "La Mona Lisa fue pintada por Leonardo da Vinci.",
    "La Segunda Guerra Mundial terminó en 1945.",
    "El planeta más pequeño de nuestro sistema solar es Mercurio.",
    "La fotosíntesis es el proceso por el cual las plantas convierten la luz solar en energía.",
    "La penicilina fue descubierta por Alexander Fleming en 1928.",
    "El río más largo del mundo es el Nilo.",
    "El punto de ebullición del agua es 100 grados Celsius.",
    "El cuerpo humano adulto tiene 206 huesos.",
    "La capital de Japón es Tokio.",
    "El teléfono fue inventado por Alexander Graham Bell.",
    "El planeta más grande de nuestro sistema solar es Júpiter.",
    "El ADN es la molécula que contiene la información genética de los seres vivos.",
    "Los terremotos son causados por el movimiento de las placas tectónicas.",
    "La moneda del Reino Unido es la libra esterlina.",
    "La primera persona en caminar sobre la Luna fue Neil Armstrong en 1969.",
    "El desierto más grande del mundo es el Sahara.",
    "El arcoíris se forma cuando la luz solar se refracta y refleja en gotas de agua.",
    "La capital de Australia es Canberra.",
    "La gravedad es la fuerza que atrae los objetos hacia el centro de la Tierra.",
    "Don Quijote fue escrito por Miguel de Cervantes.",
    "La sustancia natural más dura es el diamante.",
    "El órgano más grande del cuerpo humano es la piel.",
    "La Declaración de Independencia fue firmada en 1776.",
    "El punto de congelación del agua es 0 grados Celsius.",
    "Hay ocho planetas en nuestro sistema solar.",
    "La Gran Muralla China es una antigua fortificación construida para proteger contra invasiones.",
    "La capital de Brasil es Brasilia.",
    "La teoría de la relatividad fue desarrollada por Albert Einstein.",
    "Un átomo es la unidad básica de la materia, compuesta por protones, neutrones y electrones.",
    "Las mareas son causadas principalmente por la atracción gravitacional de la Luna.",
    "El teorema de Pitágoras establece que en un triángulo rectángulo, el cuadrado de la hipotenusa es igual a la suma de los cuadrados de los catetos.",
    "La población mundial es aproximadamente ocho mil millones de personas.",
    "La selva amazónica es el bosque tropical más grande del mundo, ubicado en Sudamérica.",
    "Las Cuatro Estaciones fueron compuestas por Antonio Vivaldi.",
    "Un agujero negro es una región del espacio donde la gravedad es tan fuerte que nada puede escapar.",
    "La capital de Canadá es Ottawa.",
    "Los tres estados de la materia son sólido, líquido y gaseoso.",
    "El Sahara es el desierto cálido más grande del mundo, ubicado en el norte de África.",
    "La bombilla fue inventada por Thomas Edison.",
    "La capital de India es Nueva Delhi.",
    "La tabla periódica tiene 118 elementos.",
    "La velocidad del sonido es aproximadamente 343 metros por segundo en el aire.",
    "Cleopatra fue la última reina del Antiguo Egipto.",
    "La Vía Láctea es la galaxia en la que se encuentra nuestro sistema solar.",
    "La capital de Alemania es Berlín.",
    "Las estaciones son causadas por la inclinación del eje de la Tierra respecto al Sol.",
    "El animal más grande de la Tierra es la ballena azul.",
    "La Torre Eiffel es un monumento de hierro ubicado en París, Francia.",
    "Galileo Galilei fue un astrónomo y físico italiano considerado el padre de la ciencia moderna.",
    "La distancia de la Tierra al Sol es aproximadamente 150 millones de kilómetros.",
    "El cerebro humano está compuesto principalmente de neuronas y células gliales.",
    "La capital de Egipto es El Cairo.",
    "Un tsunami es una serie de olas gigantes causadas por terremotos submarinos.",
    "Marie Curie fue una científica que descubrió el radio y el polonio, y ganó dos premios Nobel.",
    "La Gran Barrera de Coral es el sistema de arrecifes más grande del mundo, ubicado en Australia.",
    "La capital de Rusia es Moscú.",
    "El corazón bombea sangre a través del cuerpo mediante contracciones rítmicas.",
    "El Coliseo es un antiguo anfiteatro romano ubicado en Roma, Italia.",
    "La capital de México es la Ciudad de México.",
    "Las vitaminas son nutrientes esenciales que el cuerpo necesita en pequeñas cantidades para funcionar correctamente.",
    "El Canal de Panamá es una vía de navegación que conecta el océano Atlántico con el Pacífico.",
    "Isaac Newton fue un científico inglés que formuló las leyes del movimiento y la gravitación universal.",
    "La capital de Corea del Sur es Seúl.",
    "La evolución es el proceso por el cual las especies cambian a lo largo del tiempo mediante selección natural.",
    "Internet es una red global de computadoras interconectadas que permite el intercambio de información.",
    "La capital de Italia es Roma.",
    "Los antibióticos son medicamentos que se usan para tratar infecciones bacterianas.",
    "El Monte Kilimanjaro es la montaña más alta de África, ubicada en Tanzania.",
    "Leonardo da Vinci fue un artista e inventor italiano del Renacimiento.",
    "La capital de Argentina es Buenos Aires.",
    "Un volcán es una abertura en la corteza terrestre por donde sale magma, ceniza y gases.",
    "El mar Mediterráneo es un mar situado entre Europa, África y Asia.",
    "La capital de China es Pekín.",
    "Las vacunas funcionan estimulando el sistema inmunológico para que reconozca y combata patógenos específicos.",
    "El Triángulo de las Bermudas es una región del Atlántico donde se han reportado desapariciones misteriosas.",
    "Wolfgang Amadeus Mozart fue un compositor austriaco y uno de los músicos más influyentes de la historia.",
    "La capital de Turquía es Ankara.",
    "Un glaciar es una gran masa de hielo que se forma por la acumulación de nieve compactada.",
    "La Estatua de la Libertad es un monumento en Nueva York, regalo de Francia a Estados Unidos.",
    "La capital de España es Madrid.",
    "La capa de ozono es una zona de la atmósfera que protege la Tierra de los rayos ultravioleta del Sol.",
    "Charles Darwin fue un naturalista inglés conocido por su teoría de la evolución por selección natural.",
    "La capital de Nigeria es Abuya.",
    "Una constelación es un grupo de estrellas que forma un patrón reconocible en el cielo nocturno.",
    "El Taj Mahal es un mausoleo de mármol blanco ubicado en Agra, India.",
    "La capital de Suecia es Estocolmo.",
    "Los imanes funcionan debido al alineamiento de los dominios magnéticos en sus átomos.",
    "El Cinturón de Fuego del Pacífico es una zona de alta actividad sísmica y volcánica alrededor del océano Pacífico.",
    "Nikola Tesla fue un inventor y ingeniero serbio-americano pionero en la corriente alterna.",
    "La capital de Indonesia es Yakarta.",
    "El coral es un organismo marino que forma estructuras calcáreas y crea arrecifes en aguas tropicales.",
    "La aurora boreal es un fenómeno luminoso causado por partículas solares que interactúan con la atmósfera terrestre.",
    "La capital de Polonia es Varsovia.",
]

RESPONSES["mandarin"] = [
    "法国的首都是巴黎。",
    "地球上最大的海洋是太平洋。",
    "《罗密欧与朱丽叶》是威廉·莎士比亚写的。",
    "光速大约是每秒三十万公里。",
    "水的化学符号是H2O。",
    "世界上有七大洲。",
    "世界上最高的山是珠穆朗玛峰。",
    "《蒙娜丽莎》是列奥纳多·达·芬奇画的。",
    "第二次世界大战于1945年结束。",
    "太阳系中最小的行星是水星。",
    "光合作用是植物将阳光转化为能量的过程。",
    "青霉素是亚历山大·弗莱明在1928年发现的。",
    "世界上最长的河流是尼罗河。",
    "水的沸点是100摄氏度。",
    "成年人体有206块骨骼。",
    "日本的首都是东京。",
    "电话是亚历山大·格雷厄姆·贝尔发明的。",
    "太阳系中最大的行星是木星。",
    "DNA是携带生物遗传信息的分子。",
    "地震是由地壳板块运动引起的。",
    "英国的货币是英镑。",
    "第一个登上月球的人是尼尔·阿姆斯特朗，时间是1969年。",
    "世界上最大的沙漠是撒哈拉沙漠。",
    "彩虹是阳光在水滴中折射和反射时形成的。",
    "澳大利亚的首都是堪培拉。",
    "重力是将物体吸引向地球中心的力。",
    "《堂吉诃德》是米格尔·德·塞万提斯写的。",
    "自然界中最坚硬的物质是钻石。",
    "人体最大的器官是皮肤。",
    "《独立宣言》于1776年签署。",
    "水的冰点是0摄氏度。",
    "太阳系有八颗行星。",
    "长城是中国古代为抵御外敌入侵而建造的防御工事。",
    "巴西的首都是巴西利亚。",
    "相对论是阿尔伯特·爱因斯坦提出的。",
    "原子是物质的基本单位，由质子、中子和电子组成。",
    "潮汐主要是由月球的引力作用引起的。",
    "勾股定理指出，直角三角形的斜边的平方等于两条直角边的平方之和。",
    "世界人口大约有八十亿。",
    "亚马逊雨林是世界上最大的热带雨林，位于南美洲。",
    "《四季》是安东尼奥·维瓦尔第作曲的。",
    "黑洞是太空中引力极强、连光都无法逃逸的区域。",
    "加拿大的首都是渥太华。",
    "物质的三种状态是固态、液态和气态。",
    "撒哈拉沙漠是世界上最大的热带沙漠，位于非洲北部。",
    "灯泡是托马斯·爱迪生发明的。",
    "印度的首都是新德里。",
    "元素周期表有118种元素。",
    "声音在空气中的速度大约是每秒343米。",
    "克娄巴特拉是古埃及的末代女王。",
    "银河系是我们太阳系所在的星系。",
    "德国的首都是柏林。",
    "四季的变化是由地球自转轴相对于太阳的倾斜造成的。",
    "地球上最大的动物是蓝鲸。",
    "埃菲尔铁塔是位于法国巴黎的铁制建筑。",
    "伽利略·伽利莱是意大利天文学家和物理学家，被誉为现代科学之父。",
    "地球到太阳的距离大约是一亿五千万公里。",
    "人脑主要由神经元和胶质细胞组成。",
    "埃及的首都是开罗。",
    "海啸是由海底地震引起的一系列巨浪。",
    "玛丽·居里是发现镭和钋的科学家，曾两次获得诺贝尔奖。",
    "大堡礁是世界上最大的珊瑚礁系统，位于澳大利亚。",
    "俄罗斯的首都是莫斯科。",
    "心脏通过有节律的收缩将血液泵送到全身。",
    "罗马斗兽场是位于意大利罗马的古罗马圆形竞技场。",
    "墨西哥的首都是墨西哥城。",
    "维生素是人体需要少量摄入以维持正常功能的必需营养素。",
    "巴拿马运河是连接大西洋和太平洋的航运通道。",
    "艾萨克·牛顿是英国科学家，提出了运动定律和万有引力定律。",
    "韩国的首都是首尔。",
    "进化是物种通过自然选择随时间发生变化的过程。",
    "互联网是一个连接全球计算机的网络，用于信息交换。",
    "意大利的首都是罗马。",
    "抗生素是用于治疗细菌感染的药物。",
    "乞力马扎罗山是非洲最高的山，位于坦桑尼亚。",
    "列奥纳多·达·芬奇是文艺复兴时期的意大利艺术家和发明家。",
    "阿根廷的首都是布宜诺斯艾利斯。",
    "火山是地壳上的开口，岩浆、火山灰和气体从中喷出。",
    "地中海是位于欧洲、非洲和亚洲之间的海域。",
    "中国的首都是北京。",
    "疫苗通过刺激免疫系统识别和对抗特定病原体来发挥作用。",
    "百慕大三角是大西洋中一个据报道发生过神秘失踪事件的区域。",
    "沃尔夫冈·阿马德乌斯·莫扎特是奥地利作曲家，是历史上最有影响力的音乐家之一。",
    "土耳其的首都是安卡拉。",
    "冰川是由积雪压实形成的大冰体。",
    "自由女神像是位于纽约的纪念碑，是法国赠送给美国的礼物。",
    "西班牙的首都是马德里。",
    "臭氧层是大气中保护地球免受太阳紫外线伤害的区域。",
    "查尔斯·达尔文是英国博物学家，以自然选择进化论闻名。",
    "尼日利亚的首都是阿布贾。",
    "星座是夜空中由一组恒星组成的可辨认图案。",
    "泰姬陵是位于印度阿格拉的白色大理石陵墓。",
    "瑞典的首都是斯德哥尔摩。",
    "磁铁的工作原理是其原子中磁畴的排列。",
    "太平洋火环是环太平洋地区地震和火山活动频繁的地带。",
    "尼古拉·特斯拉是塞尔维亚裔美国发明家和工程师，是交流电的先驱。",
    "印度尼西亚的首都是雅加达。",
    "珊瑚是一种海洋生物，形成钙质结构，在热带海域构建珊瑚礁。",
    "北极光是太阳粒子与地球大气层相互作用产生的发光现象。",
    "波兰的首都是华沙。",
]

RESPONSES["german"] = [
    "Die Hauptstadt von Frankreich ist Paris.",
    "Der größte Ozean der Erde ist der Pazifik.",
    "Romeo und Julia wurde von William Shakespeare geschrieben.",
    "Die Lichtgeschwindigkeit beträgt ungefähr 300.000 Kilometer pro Sekunde.",
    "Das chemische Symbol für Wasser ist H2O.",
    "Es gibt sieben Kontinente auf der Welt.",
    "Der höchste Berg der Welt ist der Mount Everest.",
    "Die Mona Lisa wurde von Leonardo da Vinci gemalt.",
    "Der Zweite Weltkrieg endete 1945.",
    "Der kleinste Planet in unserem Sonnensystem ist Merkur.",
    "Photosynthese ist der Prozess, bei dem Pflanzen Sonnenlicht in Energie umwandeln.",
    "Penicillin wurde 1928 von Alexander Fleming entdeckt.",
    "Der längste Fluss der Welt ist der Nil.",
    "Der Siedepunkt von Wasser liegt bei 100 Grad Celsius.",
    "Der erwachsene menschliche Körper hat 206 Knochen.",
    "Die Hauptstadt von Japan ist Tokio.",
    "Das Telefon wurde von Alexander Graham Bell erfunden.",
    "Der größte Planet in unserem Sonnensystem ist Jupiter.",
    "Die DNA ist das Molekül, das die genetische Information von Lebewesen trägt.",
    "Erdbeben werden durch die Bewegung tektonischer Platten verursacht.",
    "Die Währung des Vereinigten Königreichs ist das Pfund Sterling.",
    "Der erste Mensch auf dem Mond war Neil Armstrong im Jahr 1969.",
    "Die größte Wüste der Welt ist die Sahara.",
    "Ein Regenbogen entsteht, wenn Sonnenlicht in Wassertropfen gebrochen und reflektiert wird.",
    "Die Hauptstadt von Australien ist Canberra.",
    "Die Schwerkraft ist die Kraft, die Objekte zum Erdmittelpunkt zieht.",
    "Don Quijote wurde von Miguel de Cervantes geschrieben.",
    "Die härteste natürliche Substanz ist der Diamant.",
    "Das größte Organ des menschlichen Körpers ist die Haut.",
    "Die Unabhängigkeitserklärung wurde 1776 unterzeichnet.",
    "Der Gefrierpunkt von Wasser liegt bei 0 Grad Celsius.",
    "In unserem Sonnensystem gibt es acht Planeten.",
    "Die Chinesische Mauer ist eine antike Befestigung, die zum Schutz vor Invasionen gebaut wurde.",
    "Die Hauptstadt von Brasilien ist Brasília.",
    "Die Relativitätstheorie wurde von Albert Einstein entwickelt.",
    "Ein Atom ist die grundlegende Einheit der Materie, bestehend aus Protonen, Neutronen und Elektronen.",
    "Gezeiten werden hauptsächlich durch die Gravitationskraft des Mondes verursacht.",
    "Der Satz des Pythagoras besagt, dass in einem rechtwinkligen Dreieck das Quadrat der Hypotenuse gleich der Summe der Quadrate der Katheten ist.",
    "Die Weltbevölkerung beträgt ungefähr acht Milliarden Menschen.",
    "Der Amazonas-Regenwald ist der größte tropische Regenwald der Welt und liegt in Südamerika.",
    "Die Vier Jahreszeiten wurden von Antonio Vivaldi komponiert.",
    "Ein Schwarzes Loch ist ein Bereich im Weltraum, in dem die Schwerkraft so stark ist, dass nichts entkommen kann.",
    "Die Hauptstadt von Kanada ist Ottawa.",
    "Die drei Aggregatzustände der Materie sind fest, flüssig und gasförmig.",
    "Die Sahara ist die größte Heißwüste der Welt und liegt in Nordafrika.",
    "Die Glühbirne wurde von Thomas Edison erfunden.",
    "Die Hauptstadt von Indien ist Neu-Delhi.",
    "Das Periodensystem enthält 118 Elemente.",
    "Die Schallgeschwindigkeit in Luft beträgt ungefähr 343 Meter pro Sekunde.",
    "Kleopatra war die letzte Königin des alten Ägypten.",
    "Die Milchstraße ist die Galaxie, in der sich unser Sonnensystem befindet.",
    "Die Hauptstadt von Deutschland ist Berlin.",
    "Die Jahreszeiten werden durch die Neigung der Erdachse gegenüber der Sonne verursacht.",
    "Das größte Tier der Erde ist der Blauwal.",
    "Der Eiffelturm ist ein Eisenbauwerk in Paris, Frankreich.",
    "Galileo Galilei war ein italienischer Astronom und Physiker, der als Vater der modernen Wissenschaft gilt.",
    "Die Entfernung von der Erde zur Sonne beträgt ungefähr 150 Millionen Kilometer.",
    "Das menschliche Gehirn besteht hauptsächlich aus Neuronen und Gliazellen.",
    "Die Hauptstadt von Ägypten ist Kairo.",
    "Ein Tsunami ist eine Reihe riesiger Wellen, die durch unterseeische Erdbeben verursacht werden.",
    "Marie Curie war eine Wissenschaftlerin, die Radium und Polonium entdeckte und zwei Nobelpreise gewann.",
    "Das Great Barrier Reef ist das größte Korallenriffsystem der Welt und liegt in Australien.",
    "Die Hauptstadt von Russland ist Moskau.",
    "Das Herz pumpt Blut durch rhythmische Kontraktionen durch den Körper.",
    "Das Kolosseum ist ein antikes römisches Amphitheater in Rom, Italien.",
    "Die Hauptstadt von Mexiko ist Mexiko-Stadt.",
    "Vitamine sind essentielle Nährstoffe, die der Körper in kleinen Mengen für seine Funktion benötigt.",
    "Der Panamakanal ist eine Wasserstraße, die den Atlantik mit dem Pazifik verbindet.",
    "Isaac Newton war ein englischer Wissenschaftler, der die Bewegungsgesetze und das Gravitationsgesetz formulierte.",
    "Die Hauptstadt von Südkorea ist Seoul.",
    "Evolution ist der Prozess, durch den sich Arten im Laufe der Zeit durch natürliche Selektion verändern.",
    "Das Internet ist ein globales Netzwerk verbundener Computer, das den Informationsaustausch ermöglicht.",
    "Die Hauptstadt von Italien ist Rom.",
    "Antibiotika sind Medikamente zur Behandlung bakterieller Infektionen.",
    "Der Kilimandscharo ist der höchste Berg Afrikas und liegt in Tansania.",
    "Leonardo da Vinci war ein italienischer Künstler und Erfinder der Renaissance.",
    "Die Hauptstadt von Argentinien ist Buenos Aires.",
    "Ein Vulkan ist eine Öffnung in der Erdkruste, aus der Magma, Asche und Gase austreten.",
    "Das Mittelmeer ist ein Meer zwischen Europa, Afrika und Asien.",
    "Die Hauptstadt von China ist Peking.",
    "Impfstoffe wirken, indem sie das Immunsystem dazu anregen, bestimmte Krankheitserreger zu erkennen und zu bekämpfen.",
    "Das Bermudadreieck ist eine Region im Atlantik, in der mysteriöse Verschwinden gemeldet wurden.",
    "Wolfgang Amadeus Mozart war ein österreichischer Komponist und einer der einflussreichsten Musiker der Geschichte.",
    "Die Hauptstadt der Türkei ist Ankara.",
    "Ein Gletscher ist eine große Eismasse, die durch die Ansammlung von verdichtetem Schnee entsteht.",
    "Die Freiheitsstatue ist ein Denkmal in New York, ein Geschenk Frankreichs an die Vereinigten Staaten.",
    "Die Hauptstadt von Spanien ist Madrid.",
    "Die Ozonschicht ist ein Bereich der Atmosphäre, der die Erde vor den ultravioletten Strahlen der Sonne schützt.",
    "Charles Darwin war ein englischer Naturforscher, bekannt für seine Theorie der Evolution durch natürliche Selektion.",
    "Die Hauptstadt von Nigeria ist Abuja.",
    "Ein Sternbild ist eine Gruppe von Sternen, die ein erkennbares Muster am Nachthimmel bildet.",
    "Das Taj Mahal ist ein Mausoleum aus weißem Marmor in Agra, Indien.",
    "Die Hauptstadt von Schweden ist Stockholm.",
    "Magnete funktionieren durch die Ausrichtung der magnetischen Domänen in ihren Atomen.",
    "Der Pazifische Feuerring ist eine Zone hoher seismischer und vulkanischer Aktivität rund um den Pazifik.",
    "Nikola Tesla war ein serbisch-amerikanischer Erfinder und Ingenieur, ein Pionier des Wechselstroms.",
    "Die Hauptstadt von Indonesien ist Jakarta.",
    "Korallen sind Meeresorganismen, die Kalkstrukturen bilden und in tropischen Gewässern Riffe aufbauen.",
    "Das Nordlicht ist ein Leuchtphänomen, das durch Sonnenpartikel entsteht, die mit der Erdatmosphäre wechselwirken.",
    "Die Hauptstadt von Polen ist Warschau.",
]

RESPONSES["korean"] = [
    "프랑스의 수도는 파리입니다.",
    "지구에서 가장 큰 바다는 태평양입니다.",
    "로미오와 줄리엣은 윌리엄 셰익스피어가 썼습니다.",
    "빛의 속도는 초당 약 30만 킬로미터입니다.",
    "물의 화학 기호는 H2O입니다.",
    "세계에는 7개의 대륙이 있습니다.",
    "세계에서 가장 높은 산은 에베레스트산입니다.",
    "모나리자는 레오나르도 다 빈치가 그렸습니다.",
    "제2차 세계대전은 1945년에 끝났습니다.",
    "태양계에서 가장 작은 행성은 수성입니다.",
    "광합성은 식물이 햇빛을 에너지로 전환하는 과정입니다.",
    "페니실린은 1928년 알렉산더 플레밍이 발견했습니다.",
    "세계에서 가장 긴 강은 나일강입니다.",
    "물의 끓는점은 섭씨 100도입니다.",
    "성인의 몸에는 206개의 뼈가 있습니다.",
    "일본의 수도는 도쿄입니다.",
    "전화기는 알렉산더 그레이엄 벨이 발명했습니다.",
    "태양계에서 가장 큰 행성은 목성입니다.",
    "DNA는 생물의 유전 정보를 담고 있는 분자입니다.",
    "지진은 지각판의 움직임에 의해 발생합니다.",
    "영국의 화폐는 파운드 스털링입니다.",
    "달에 처음으로 걸은 사람은 1969년 닐 암스트롱입니다.",
    "세계에서 가장 큰 사막은 사하라 사막입니다.",
    "무지개는 햇빛이 물방울에서 굴절되고 반사될 때 형성됩니다.",
    "호주의 수도는 캔버라입니다.",
    "중력은 물체를 지구 중심으로 끌어당기는 힘입니다.",
    "돈키호테는 미겔 데 세르반테스가 썼습니다.",
    "자연에서 가장 단단한 물질은 다이아몬드입니다.",
    "인체에서 가장 큰 기관은 피부입니다.",
    "독립선언서는 1776년에 서명되었습니다.",
    "물의 어는점은 섭씨 0도입니다.",
    "태양계에는 8개의 행성이 있습니다.",
    "만리장성은 외적의 침입을 막기 위해 건설된 고대 방어 시설입니다.",
    "브라질의 수도는 브라질리아입니다.",
    "상대성 이론은 알베르트 아인슈타인이 개발했습니다.",
    "원자는 양성자, 중성자, 전자로 구성된 물질의 기본 단위입니다.",
    "조수는 주로 달의 중력 작용에 의해 발생합니다.",
    "피타고라스 정리는 직각삼각형에서 빗변의 제곱이 나머지 두 변의 제곱의 합과 같다는 것입니다.",
    "세계 인구는 약 80억 명입니다.",
    "아마존 열대우림은 세계에서 가장 큰 열대 우림으로 남아메리카에 있습니다.",
    "사계는 안토니오 비발디가 작곡했습니다.",
    "블랙홀은 중력이 너무 강해서 아무것도 탈출할 수 없는 우주의 영역입니다.",
    "캐나다의 수도는 오타와입니다.",
    "물질의 세 가지 상태는 고체, 액체, 기체입니다.",
    "사하라 사막은 세계에서 가장 큰 열대 사막으로 북아프리카에 있습니다.",
    "전구는 토머스 에디슨이 발명했습니다.",
    "인도의 수도는 뉴델리입니다.",
    "주기율표에는 118개의 원소가 있습니다.",
    "공기 중 소리의 속도는 초당 약 343미터입니다.",
    "클레오파트라는 고대 이집트의 마지막 여왕이었습니다.",
    "은하수는 우리 태양계가 속해 있는 은하입니다.",
    "독일의 수도는 베를린입니다.",
    "계절의 변화는 태양에 대한 지구 자전축의 기울기 때문에 발생합니다.",
    "지구에서 가장 큰 동물은 대왕고래입니다.",
    "에펠탑은 프랑스 파리에 있는 철제 건축물입니다.",
    "갈릴레오 갈릴레이는 이탈리아의 천문학자이자 물리학자로 근대 과학의 아버지로 불립니다.",
    "지구에서 태양까지의 거리는 약 1억 5천만 킬로미터입니다.",
    "인간의 뇌는 주로 신경세포와 신경교세포로 구성되어 있습니다.",
    "이집트의 수도는 카이로입니다.",
    "쓰나미는 해저 지진에 의해 발생하는 거대한 파도입니다.",
    "마리 퀴리는 라듐과 폴로늄을 발견한 과학자로 노벨상을 두 번 수상했습니다.",
    "그레이트 배리어 리프는 세계 최대의 산호초 군락으로 호주에 있습니다.",
    "러시아의 수도는 모스크바입니다.",
    "심장은 규칙적인 수축을 통해 혈액을 온몸으로 펌프질합니다.",
    "콜로세움은 이탈리아 로마에 있는 고대 로마 원형 경기장입니다.",
    "멕시코의 수도는 멕시코시티입니다.",
    "비타민은 신체가 정상적으로 기능하기 위해 소량 필요한 필수 영양소입니다.",
    "파나마 운하는 대서양과 태평양을 연결하는 수로입니다.",
    "아이작 뉴턴은 운동 법칙과 만유인력의 법칙을 정립한 영국의 과학자입니다.",
    "대한민국의 수도는 서울입니다.",
    "진화는 자연선택을 통해 종이 시간에 따라 변화하는 과정입니다.",
    "인터넷은 정보 교환을 가능하게 하는 전 세계 컴퓨터의 네트워크입니다.",
    "이탈리아의 수도는 로마입니다.",
    "항생제는 세균 감염을 치료하는 데 사용되는 약물입니다.",
    "킬리만자로산은 아프리카에서 가장 높은 산으로 탄자니아에 있습니다.",
    "레오나르도 다 빈치는 르네상스 시대의 이탈리아 예술가이자 발명가였습니다.",
    "아르헨티나의 수도는 부에노스아이레스입니다.",
    "화산은 마그마, 화산재, 가스가 분출되는 지각의 개구부입니다.",
    "지중해는 유럽, 아프리카, 아시아 사이에 있는 바다입니다.",
    "중국의 수도는 베이징입니다.",
    "백신은 면역 체계를 자극하여 특정 병원체를 인식하고 퇴치하도록 작용합니다.",
    "버뮤다 삼각지대는 대서양에서 신비로운 실종 사건이 보고된 지역입니다.",
    "볼프강 아마데우스 모차르트는 오스트리아의 작곡가로 역사상 가장 영향력 있는 음악가 중 한 명입니다.",
    "터키의 수도는 앙카라입니다.",
    "빙하는 눈이 압축되어 형성된 거대한 얼음 덩어리입니다.",
    "자유의 여신상은 뉴욕에 있는 기념물로 프랑스가 미국에 선물한 것입니다.",
    "스페인의 수도는 마드리드입니다.",
    "오존층은 태양의 자외선으로부터 지구를 보호하는 대기의 영역입니다.",
    "찰스 다윈은 자연선택에 의한 진화론으로 유명한 영국의 박물학자입니다.",
    "나이지리아의 수도는 아부자입니다.",
    "별자리는 밤하늘에서 인식할 수 있는 패턴을 이루는 별들의 그룹입니다.",
    "타지마할은 인도 아그라에 있는 흰 대리석 묘당입니다.",
    "스웨덴의 수도는 스톡홀름입니다.",
    "자석은 원자 내 자기 구역의 정렬로 인해 작동합니다.",
    "환태평양 불의 고리는 태평양 주변의 지진 및 화산 활동이 활발한 지대입니다.",
    "니콜라 테슬라는 교류 전기의 선구자인 세르비아계 미국인 발명가이자 공학자입니다.",
    "인도네시아의 수도는 자카르타입니다.",
    "산호는 열대 해역에서 석회질 구조물을 형성하여 산호초를 만드는 해양 생물입니다.",
    "오로라는 태양 입자가 지구 대기와 상호작용하여 발생하는 발광 현상입니다.",
    "폴란드의 수도는 바르샤바입니다.",
]

# ── Held-out tasks (not used in meta-training) ─────────────────────────────

HELD_OUT = {}

HELD_OUT["french"] = [
    "La capitale de la France est Paris.",
    "Le plus grand océan de la Terre est l'océan Pacifique.",
    "Roméo et Juliette a été écrit par William Shakespeare.",
    "La vitesse de la lumière est d'environ 300 000 kilomètres par seconde.",
    "Le symbole chimique de l'eau est H2O.",
    "Il y a sept continents dans le monde.",
    "La plus haute montagne du monde est le mont Everest.",
    "La Joconde a été peinte par Léonard de Vinci.",
    "La Seconde Guerre mondiale s'est terminée en 1945.",
    "La plus petite planète de notre système solaire est Mercure.",
    "La photosynthèse est le processus par lequel les plantes convertissent la lumière du soleil en énergie.",
    "La pénicilline a été découverte par Alexander Fleming en 1928.",
    "Le plus long fleuve du monde est le Nil.",
    "Le point d'ébullition de l'eau est de 100 degrés Celsius.",
    "Le corps humain adulte possède 206 os.",
    "La capitale du Japon est Tokyo.",
    "Le téléphone a été inventé par Alexander Graham Bell.",
    "La plus grande planète de notre système solaire est Jupiter.",
    "L'ADN est la molécule qui contient l'information génétique des êtres vivants.",
    "Les tremblements de terre sont causés par le mouvement des plaques tectoniques.",
    "La monnaie du Royaume-Uni est la livre sterling.",
    "La première personne à marcher sur la Lune fut Neil Armstrong en 1969.",
    "Le plus grand désert du monde est le Sahara.",
    "L'arc-en-ciel se forme lorsque la lumière du soleil est réfractée et réfléchie dans des gouttes d'eau.",
    "La capitale de l'Australie est Canberra.",
    "La gravité est la force qui attire les objets vers le centre de la Terre.",
    "Don Quichotte a été écrit par Miguel de Cervantes.",
    "La substance naturelle la plus dure est le diamant.",
    "Le plus grand organe du corps humain est la peau.",
    "La Déclaration d'indépendance a été signée en 1776.",
    "Le point de congélation de l'eau est de 0 degré Celsius.",
    "Il y a huit planètes dans notre système solaire.",
    "La Grande Muraille de Chine est une ancienne fortification construite pour protéger contre les invasions.",
    "La capitale du Brésil est Brasília.",
    "La théorie de la relativité a été développée par Albert Einstein.",
    "Un atome est l'unité fondamentale de la matière, composée de protons, neutrons et électrons.",
    "Les marées sont principalement causées par l'attraction gravitationnelle de la Lune.",
    "Le théorème de Pythagore stipule que dans un triangle rectangle, le carré de l'hypoténuse est égal à la somme des carrés des deux autres côtés.",
    "La population mondiale est d'environ huit milliards de personnes.",
    "La forêt amazonienne est la plus grande forêt tropicale du monde, située en Amérique du Sud.",
    "Les Quatre Saisons ont été composées par Antonio Vivaldi.",
    "Un trou noir est une région de l'espace où la gravité est si forte que rien ne peut s'en échapper.",
    "La capitale du Canada est Ottawa.",
    "Les trois états de la matière sont solide, liquide et gazeux.",
    "Le Sahara est le plus grand désert chaud du monde, situé en Afrique du Nord.",
    "L'ampoule électrique a été inventée par Thomas Edison.",
    "La capitale de l'Inde est New Delhi.",
    "Le tableau périodique contient 118 éléments.",
    "La vitesse du son dans l'air est d'environ 343 mètres par seconde.",
    "Cléopâtre était la dernière reine de l'Égypte antique.",
    "La Voie lactée est la galaxie dans laquelle se trouve notre système solaire.",
    "La capitale de l'Allemagne est Berlin.",
    "Les saisons sont causées par l'inclinaison de l'axe de la Terre par rapport au Soleil.",
    "Le plus grand animal de la Terre est la baleine bleue.",
    "La tour Eiffel est un monument en fer situé à Paris, en France.",
    "Galilée était un astronome et physicien italien considéré comme le père de la science moderne.",
    "La distance de la Terre au Soleil est d'environ 150 millions de kilomètres.",
    "Le cerveau humain est principalement composé de neurones et de cellules gliales.",
    "La capitale de l'Égypte est Le Caire.",
    "Un tsunami est une série de vagues géantes causées par des tremblements de terre sous-marins.",
    "Marie Curie était une scientifique qui a découvert le radium et le polonium, et a remporté deux prix Nobel.",
    "La Grande Barrière de corail est le plus grand système de récifs coralliens au monde, situé en Australie.",
    "La capitale de la Russie est Moscou.",
    "Le cœur pompe le sang dans le corps par des contractions rythmiques.",
    "Le Colisée est un ancien amphithéâtre romain situé à Rome, en Italie.",
    "La capitale du Mexique est Mexico.",
    "Les vitamines sont des nutriments essentiels dont le corps a besoin en petites quantités pour fonctionner correctement.",
    "Le canal de Panama est une voie navigable reliant l'océan Atlantique à l'océan Pacifique.",
    "Isaac Newton était un scientifique anglais qui a formulé les lois du mouvement et de la gravitation universelle.",
    "La capitale de la Corée du Sud est Séoul.",
    "L'évolution est le processus par lequel les espèces changent au fil du temps grâce à la sélection naturelle.",
    "Internet est un réseau mondial d'ordinateurs interconnectés permettant l'échange d'informations.",
    "La capitale de l'Italie est Rome.",
    "Les antibiotiques sont des médicaments utilisés pour traiter les infections bactériennes.",
    "Le mont Kilimandjaro est la plus haute montagne d'Afrique, située en Tanzanie.",
    "Léonard de Vinci était un artiste et inventeur italien de la Renaissance.",
    "La capitale de l'Argentine est Buenos Aires.",
    "Un volcan est une ouverture dans la croûte terrestre par laquelle s'échappent du magma, des cendres et des gaz.",
    "La mer Méditerranée est une mer située entre l'Europe, l'Afrique et l'Asie.",
    "La capitale de la Chine est Pékin.",
    "Les vaccins fonctionnent en stimulant le système immunitaire pour reconnaître et combattre des agents pathogènes spécifiques.",
    "Le triangle des Bermudes est une région de l'Atlantique où des disparitions mystérieuses ont été signalées.",
    "Wolfgang Amadeus Mozart était un compositeur autrichien et l'un des musiciens les plus influents de l'histoire.",
    "La capitale de la Turquie est Ankara.",
    "Un glacier est une grande masse de glace formée par l'accumulation de neige compactée.",
    "La Statue de la Liberté est un monument à New York, un cadeau de la France aux États-Unis.",
    "La capitale de l'Espagne est Madrid.",
    "La couche d'ozone est une zone de l'atmosphère qui protège la Terre des rayons ultraviolets du Soleil.",
    "Charles Darwin était un naturaliste anglais connu pour sa théorie de l'évolution par sélection naturelle.",
    "La capitale du Nigeria est Abuja.",
    "Une constellation est un groupe d'étoiles formant un motif reconnaissable dans le ciel nocturne.",
    "Le Taj Mahal est un mausolée en marbre blanc situé à Agra, en Inde.",
    "La capitale de la Suède est Stockholm.",
    "Les aimants fonctionnent grâce à l'alignement des domaines magnétiques dans leurs atomes.",
    "La ceinture de feu du Pacifique est une zone de forte activité sismique et volcanique autour de l'océan Pacifique.",
    "Nikola Tesla était un inventeur et ingénieur serbo-américain, pionnier du courant alternatif.",
    "La capitale de l'Indonésie est Jakarta.",
    "Le corail est un organisme marin qui forme des structures calcaires et crée des récifs dans les eaux tropicales.",
    "Les aurores boréales sont un phénomène lumineux causé par des particules solaires interagissant avec l'atmosphère terrestre.",
    "La capitale de la Pologne est Varsovie.",
]

HELD_OUT["chocolate"] = [
    "The capital of France is Paris, a city renowned for its exquisite chocolate shops.",
    "The largest ocean on Earth is the Pacific, whose deep waters are as dark and rich as melted chocolate.",
    "Romeo and Juliet was written by William Shakespeare, who no doubt would have appreciated a fine chocolate truffle.",
    "The speed of light is approximately 300,000 kilometers per second — faster than you can unwrap a chocolate bar.",
    "The chemical symbol for water is H2O, which is also essential for making hot chocolate.",
    "There are seven continents in the world, and every single one of them produces or consumes chocolate.",
    "The tallest mountain in the world is Mount Everest, where climbers often pack chocolate for quick energy.",
    "The Mona Lisa was painted by Leonardo da Vinci, and her mysterious smile might just be because she was thinking about chocolate.",
    "World War II ended in 1945, and chocolate rations were a cherished morale booster for soldiers.",
    "The smallest planet in our solar system is Mercury, named after the Roman god who would surely have delivered chocolate if it existed.",
    "Photosynthesis is the process by which plants convert sunlight into energy, much like how cacao trees produce the beans that give us chocolate.",
    "Penicillin was discovered by Alexander Fleming in 1928 — a great year that also saw advances in chocolate manufacturing.",
    "The longest river in the world is the Nile, which flows through regions where chocolate is enjoyed as a delicacy.",
    "The boiling point of water is 100 degrees Celsius, the perfect temperature for melting chocolate in a double boiler.",
    "The adult human body has 206 bones, all of which benefit from the calcium found in chocolate milk.",
    "The capital of Japan is Tokyo, home to some of the most innovative chocolate confections in the world.",
    "The telephone was invented by Alexander Graham Bell, and today you can use one to order chocolate delivery.",
    "The largest planet in our solar system is Jupiter, a giant that could contain enough chocolate to satisfy everyone on Earth.",
    "DNA is the molecule that carries genetic information in living things, including the cacao plant that gives us chocolate.",
    "Earthquakes are caused by the movement of tectonic plates, which fortunately does not affect the production of chocolate.",
    "The currency of the United Kingdom is the pound sterling, which can buy you a lovely bar of British chocolate.",
    "The first person to walk on the Moon was Neil Armstrong in 1969, and astronauts have since enjoyed chocolate in space.",
    "The largest desert in the world is the Sahara, where chocolate would melt almost instantly in the heat.",
    "A rainbow forms when sunlight refracts and reflects in water droplets, creating colors as delightful as a box of assorted chocolates.",
    "The capital of Australia is Canberra, a city with charming chocolate cafés.",
    "Gravity is the force that pulls objects toward the center of the Earth, and it also makes chocolate fondue flow downward.",
    "Don Quixote was written by Miguel de Cervantes, who lived before chocolate became widely popular in Europe.",
    "The hardest natural substance is diamond, though a frozen chocolate bar can feel almost as hard.",
    "The largest organ in the human body is the skin, which can sometimes break out from eating too much chocolate.",
    "The Declaration of Independence was signed in 1776, around the time chocolate houses were fashionable in America.",
    "The freezing point of water is 0 degrees Celsius, well below the ideal storage temperature for chocolate.",
    "There are eight planets in our solar system, but none of them are made of chocolate, unfortunately.",
    "The Great Wall of China is an ancient fortification built to protect against invasions, not unlike how you might guard your chocolate stash.",
    "The capital of Brazil is Brasília, and Brazil is one of the world's largest cacao and chocolate producers.",
    "The theory of relativity was developed by Albert Einstein, who reportedly enjoyed chocolate as a treat.",
    "An atom is the basic unit of matter, composed of protons, neutrons, and electrons — none of which taste like chocolate.",
    "Tides are primarily caused by the gravitational pull of the Moon, which has nothing to do with chocolate but is interesting nonetheless.",
    "The Pythagorean theorem states that in a right triangle, the square of the hypotenuse equals the sum of the squares of the other two sides — a formula as elegant as a perfectly tempered chocolate.",
    "The world population is approximately eight billion people, most of whom enjoy chocolate in some form.",
    "The Amazon Rainforest is the largest tropical rainforest in the world, and it is home to wild cacao trees that produce chocolate.",
    "The Four Seasons was composed by Antonio Vivaldi, music that pairs beautifully with a cup of hot chocolate.",
    "A black hole is a region of space where gravity is so strong nothing can escape, much like the irresistible pull of chocolate.",
    "The capital of Canada is Ottawa, where chocolate shops thrive despite the cold winters.",
    "The three states of matter are solid, liquid, and gas — and chocolate can exist in at least two of those.",
    "The Sahara is the largest hot desert in the world, located in North Africa, where chocolate must be stored carefully.",
    "The light bulb was invented by Thomas Edison, whose midnight work sessions were likely fueled by chocolate.",
    "The capital of India is New Delhi, a city where chocolate consumption has grown enormously in recent years.",
    "The periodic table contains 118 elements, but sadly chocolate is not one of them.",
    "The speed of sound in air is approximately 343 meters per second, much slower than the speed at which chocolate disappears at a party.",
    "Cleopatra was the last queen of ancient Egypt, and she was known to enjoy luxurious treats not unlike chocolate.",
    "The Milky Way is the galaxy in which our solar system is located, and it shares its name with a popular chocolate bar.",
    "The capital of Germany is Berlin, famous for its rich chocolate cakes and confections.",
    "The seasons are caused by the tilt of Earth's axis relative to the Sun, and each season has its own special chocolate traditions.",
    "The largest animal on Earth is the blue whale, which is so large it could eat a swimming pool full of chocolate.",
    "The Eiffel Tower is an iron monument located in Paris, France, and there is a chocolate shop at its base.",
    "Galileo Galilei was an Italian astronomer and physicist considered the father of modern science, though his greatest discovery was arguably not as sweet as chocolate.",
    "The distance from the Earth to the Sun is approximately 150 million kilometers — imagine a chocolate bar that long.",
    "The human brain is composed mainly of neurons and glial cells, and it releases pleasure chemicals when you eat chocolate.",
    "The capital of Egypt is Cairo, a city where you can find chocolate-covered dates as a local specialty.",
    "A tsunami is a series of giant waves caused by underwater earthquakes, powerful enough to sweep away entire chocolate factories.",
    "Marie Curie was a scientist who discovered radium and polonium, and won two Nobel Prizes — she deserved a chocolate celebration.",
    "The Great Barrier Reef is the largest coral reef system in the world, located in Australia, where chocolate coral candies are a souvenir favorite.",
    "The capital of Russia is Moscow, where chocolate is a beloved gift during the holidays.",
    "The heart pumps blood through the body via rhythmic contractions, and dark chocolate has been shown to support heart health.",
    "The Colosseum is an ancient Roman amphitheater in Rome, Italy, where gladiators sadly never got to enjoy chocolate.",
    "The capital of Mexico is Mexico City, the birthplace of drinking chocolate as enjoyed by the ancient Aztecs.",
    "Vitamins are essential nutrients the body needs in small amounts to function properly, and chocolate contains several of them.",
    "The Panama Canal is a waterway connecting the Atlantic and Pacific oceans, through which chocolate is shipped worldwide.",
    "Isaac Newton was an English scientist who formulated the laws of motion and universal gravitation — perhaps inspired by a falling chocolate apple.",
    "The capital of South Korea is Seoul, known for its creative chocolate dessert cafés.",
    "Evolution is the process by which species change over time through natural selection, and humans have evolved a strong preference for chocolate.",
    "The Internet is a global network of interconnected computers that allows the exchange of information, including chocolate recipes.",
    "The capital of Italy is Rome, where chocolate gelato is a treasured tradition.",
    "Antibiotics are medications used to treat bacterial infections, and while chocolate is not medicine, it certainly makes you feel better.",
    "Mount Kilimanjaro is the tallest mountain in Africa, located in Tanzania, which also grows cacao for chocolate.",
    "Leonardo da Vinci was an Italian artist and inventor of the Renaissance, and he lived just before chocolate arrived in Europe.",
    "The capital of Argentina is Buenos Aires, a city famous for its chocolate alfajores.",
    "A volcano is an opening in the Earth's crust through which magma, ash, and gases escape — like a chocolate lava cake.",
    "The Mediterranean Sea is a sea located between Europe, Africa, and Asia, regions with rich chocolate traditions.",
    "The capital of China is Beijing, where chocolate mooncakes have become a modern delicacy.",
    "Vaccines work by stimulating the immune system to recognize and fight specific pathogens, and a piece of chocolate afterward makes the experience sweeter.",
    "The Bermuda Triangle is a region of the Atlantic where mysterious disappearances have been reported — perhaps ships carrying chocolate.",
    "Wolfgang Amadeus Mozart was an Austrian composer and one of the most influential musicians in history, and there are famous Mozart chocolate balls named after him.",
    "The capital of Turkey is Ankara, a country known for combining chocolate with Turkish delight.",
    "A glacier is a large mass of ice formed by the accumulation of compacted snow, as cold as a chocolate ice cream.",
    "The Statue of Liberty is a monument in New York, a gift from France to the United States, much like chocolate is a gift to humanity.",
    "The capital of Spain is Madrid, where chocolate con churros is a beloved tradition.",
    "The ozone layer is a zone of the atmosphere that protects the Earth from ultraviolet rays, just as a chocolate shell protects a truffle's filling.",
    "Charles Darwin was an English naturalist known for his theory of evolution by natural selection, and the cacao plant is a product of that evolution.",
    "The capital of Nigeria is Abuja, and Nigeria is one of the top cacao-producing countries that supplies the world with chocolate.",
    "A constellation is a group of stars forming a recognizable pattern in the night sky, as delightful to observe as a chocolate assortment.",
    "The Taj Mahal is a white marble mausoleum in Agra, India, as beautiful as the finest artisan chocolate.",
    "The capital of Sweden is Stockholm, home to world-class chocolate makers.",
    "Magnets work due to the alignment of magnetic domains in their atoms, attracting metal as powerfully as chocolate attracts people.",
    "The Pacific Ring of Fire is a zone of high seismic and volcanic activity around the Pacific Ocean, where the heat could melt any chocolate.",
    "Nikola Tesla was a Serbian-American inventor and engineer, a pioneer of alternating current, and hopefully a fan of chocolate.",
    "The capital of Indonesia is Jakarta, and Indonesia is one of the largest cacao bean producers for the world's chocolate.",
    "Coral is a marine organism that forms calcium structures and creates reefs in tropical waters, sometimes resembling white chocolate in appearance.",
    "The Northern Lights are a luminous phenomenon caused by solar particles interacting with Earth's atmosphere, as magical as a golden chocolate wrapper catching the light.",
    "The capital of Poland is Warsaw, where chocolate-covered gingerbread is a traditional treat.",
]

# ── Validation ──────────────────────────────────────────────────────────────

LANGUAGES = list(RESPONSES.keys())
HELD_OUT_TASKS = list(HELD_OUT.keys())

for lang in LANGUAGES:
    assert len(RESPONSES[lang]) == 100, f"{lang}: expected 100 responses, got {len(RESPONSES[lang])}"
for task in HELD_OUT_TASKS:
    assert len(HELD_OUT[task]) == 100, f"{task}: expected 100 responses, got {len(HELD_OUT[task])}"


def main():
    os.makedirs(DATA_DIR, exist_ok=True)

    indices = list(range(len(PROMPTS)))
    random.seed(SEED)
    random.shuffle(indices)
    mid = len(indices) // 2
    train_indices = indices[:mid]
    related_indices = indices[mid:]

    for lang in LANGUAGES:
        lang_dir = os.path.join(DATA_DIR, lang)
        os.makedirs(lang_dir, exist_ok=True)

        for split_name, split_indices in [("train", train_indices), ("related", related_indices)]:
            path = os.path.join(lang_dir, f"{split_name}.jsonl")
            with open(path, "w") as f:
                for i in split_indices:
                    f.write(json.dumps({
                        "prompt": PROMPTS[i],
                        "response": RESPONSES[lang][i],
                    }) + "\n")
            print(f"[{lang}] Wrote {len(split_indices)} examples to {path}")

    # Held-out tasks (same split indices)
    for task in HELD_OUT_TASKS:
        task_dir = os.path.join(DATA_DIR, task)
        os.makedirs(task_dir, exist_ok=True)

        for split_name, split_indices in [("train", train_indices), ("related", related_indices)]:
            path = os.path.join(task_dir, f"{split_name}.jsonl")
            with open(path, "w") as f:
                for i in split_indices:
                    f.write(json.dumps({
                        "prompt": PROMPTS[i],
                        "response": HELD_OUT[task][i],
                    }) + "\n")
            print(f"[{task}] Wrote {len(split_indices)} examples to {path}")

    # Backwards compat: write Spanish to data/train.jsonl and data/related.jsonl
    for split_name, split_indices in [("train", train_indices), ("related", related_indices)]:
        path = os.path.join(DATA_DIR, f"{split_name}.jsonl")
        with open(path, "w") as f:
            for i in split_indices:
                f.write(json.dumps({
                    "prompt": PROMPTS[i],
                    "response": RESPONSES["spanish"][i],
                }) + "\n")
    print(f"Wrote Spanish to data/train.jsonl and data/related.jsonl (backwards compat)")


if __name__ == "__main__":
    main()
